-- 기본값을 정하는 DEFAULT

-- 방법1, 테이블 생성시 기본값 추가
CREATE TABLE EMP_DEFAULT (
    EMPNO NUMBER,
    ENAME VARCHAR2(20),
    HIREDATE DATE DEFAULT SYSDATE
);
-- 방법2, ALTER TABLE로 기본값 추가
ALTER TABLE EMP_DEFAULT ADD (SAL NUMBER DEFAULT 1000);

-- 제약조건 확인
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMP_DEFAULT';
-- 제약조건 삭제
ALTER TABLE EMP_DEFAULT MODIFY (SAL DEFAULT NULL); -- 기본값 제거

-- 샘플 데이터 추가
INSERT INTO EMP_DEFAULT (EMPNO, ENAME) VALUES (1, '홍길동'); -- HIREDATE는 SYSDATE 기본값
SELECT * FROM EMP_DEFAULT;

-- 테이블 생성, 제약조건 설정, 샘플 데이터 입력, 제약 조건 확인
-- 퀴즈1
-- 테이블명 : EMP_MEMBER, 컬럼 : ID NUMBER, NAME VARCHAR2, REGDATE DATE
-- REGDATE 제약 조건 DEFAULT 이용하고 현재 날짜로 입력하기
CREATE TABLE EMP_MEMBER (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE
);
-- 제약 조건 확인
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'EMP_MEMBER';
-- 샘플 데이터 추가
INSERT INTO EMP_MEMBER (ID, NAME) VALUES (1, '홍길동');
SELECT * FROM EMP_MEMBER;

-- 퀴즈2
-- 테이블명 : PRODUCT, 컬럼 : PCODE VARCHAR2, PNAME VARCHAR2, USE_YN CHAR(1)
-- USE_YN CHAR(1) DEFAULT 'Y'로 설정하기
CREATE TABLE PRODUCT (
    PCODE VARCHAR2(20) PRIMARY KEY,
    PNAME VARCHAR2(50) NOT NULL,
    USE_YN CHAR(1) DEFAULT 'Y'
);
-- 제약 조건 확인
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'PRODUCT';
-- 샘플 데이터 추가
INSERT INTO PRODUCT (PCODE, PNAME) VALUES ('P001', '노트북');
SELECT * FROM PRODUCT;

-- 퀴즈3
-- 테이블명 : INVENTORY , 컬럼 : ITEM_ID NUMBER, QUANTITY NUMBER
-- QUANTITY DEFAULT 기본 수량 10으로 설정해보기
CREATE TABLE INVENTORY (
    ITEM_ID NUMBER PRIMARY KEY,
    QUANTITY NUMBER DEFAULT 10
);
-- 제약 조건 확인
SELECT * FROM USER_TAB_COLUMNS WHERE TABLE_NAME = 'INVENTORY';
-- 샘플 데이터 추가
INSERT INTO INVENTORY (ITEM_ID) VALUES (1);
SELECT * FROM INVENTORY;