SELECT ENAME, HIREDATE, DEPTNO FROM EMP WHERE EMPNO = 7369;

SELECT * FROM EMP WHERE ENAME = 'ALLEN';

SELECT * FROM EMP WHERE JOB != 'MANAGER';

SELECT ENAME, JOB, SAL FROM EMP WHERE SAL > 1600 AND SAL < 3000;

SELECT * FROM EMP WHERE ENAME LIKE '_A%';

SELECT * FROM EMP WHERE HIREDATE < TO_DATE('1981/12/09', 'YYYY/MM/DD');

SELECT * FROM EMP WHERE JOB IN('MANAGER', 'SALESMAN');

SELECT * FROM EMP WHERE COMM IS NOT NULL;

SELECT E.ENAME, D.DNAME, E.SAL FROM EMP E
JOIN DEPT D ON E.DEPTNO = D.DEPTNO 
WHERE E.DEPTNO = 30 AND E.SAL >= 1500;

SELECT * FROM EMP ORDER BY DEPTNO DESC, ENAME ASC;

SELECT DEPTNO, JOB, AVG(SAL) AS 평균급여, COUNT(*) AS 사원수
FROM EMP GROUP BY DEPTNO, JOB;

SELECT DECODE(MOD(EMPNO, 3), 0, 'A팀', 1, 'B팀', 2, 'C팀')
AS teamName, ENAME, JOB, DEPTNO FROM EMP;

SELECT E.DEPTNO, E.ENAME, D.DNAME FROM 
EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO;

CREATE USER test IDENTIFIED BY 12345;

GRANT CONNECT, RESOURCE TO test;

GRANT CREATE VIEW TO test;
CREATE VIEW emp_dno AS
SELECT EMPNO, ENAME, DEPTNO FROM EMP
WHERE DEPTNO = 30;